title: SEARIC MDIO
footer_credit: SEARIC MDIO
url: "https://rotawallet.searicmdio.org"
baseurl: ""
timezone: Asia/Kolkata

description: South East Asia Rotaract Information Center

markdown: kramdown
# highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

# plugins:
#   - jekyll-sitemap
#   - jekyll-feed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  subwallet:
    output: true
    permalink: /:path/

include:
  - _redirects
